config_map:
  - name: ITEM_MS_URI
    value: http://wiremock.{{ project }}.svc:8080/todo-ui/item-ms
  - name: LIST_MS_URI
    value: http://wiremock.{{ project }}.svc:8080/todo-ui/list-ms
  - name: JAEGER_SERVICE_NAME
  - name: JAEGER_SERVICE_NAME
    value: "{{ stage }}-todo-ui"
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: jaeger-agent.todo-monitoring.svc:5778    
  - name: JAEGER_AGENT_HOST
    value: jaeger-agent.todo-monitoring.svc           