config_map:
  - name: ITEM_MS_URI
    value: "http://list-ms.{{ project }}.svc:8080"
  - name: LIST_MS_URI
    value: "http://list-ms.{{ project }}.svc:8080"
  - name: JAEGER_SERVICE_NAME
    value: todo-ui
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: "jaeger-agent.{{ project }}.svc:5778"    
  - name: JAEGER_AGENT_HOST
    value: "jaeger-agent.{{ project }}.svc"      