config_map:
  - name: BANK_MS_SERVICE_URI
    value: "http://bank-ms.{{ project }}.svc:8080"
  - name: WALLET_MS_SERVICE_URI
    value: "http://wallet-ms.{{ project }}.svc:8080"
  - name: CURRENCY_CONVERTER_MS_SERVICE_URI
    value: "http://currency-converter-ms.{{ project }}.svc:8080"
  - name: JAEGER_SERVICE_NAME
    value: console-ui
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: "jaeger-agent.{{ project }}.svc:5778"    
  - name: JAEGER_AGENT_HOST
    value: "jaeger-agent.{{ project }}.svc"      