config_map:
  - name: BANK_MS_SERVICE_URI
    value: http://bluebank-ms.blockchain-demo-prod.svc:8080
  - name: WALLET_MS_SERVICE_URI
    value: http://bluewallet-ms.blockchain-demo-prod.svc:8080
  - name: CURRENCY_CONVERTER_MS_SERVICE_URI
    value: http://bluecurrency-converter-ms.blockchain-demo-prod.svc:8080
  - name: JAEGER_SERVICE_NAME
    value: blue-console-ui
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: jaeger-agent.blockchain-demo-monitoring.svc:5778    
  - name: JAEGER_AGENT_HOST
    value: jaeger-agent.blockchain-demo-monitoring.svc      