config_map:
  - name: BANK_MS_SERVICE_URI
    value: http://bank-ms.blockchain-demo-test.svc:8080
  - name: WALLET_MS_SERVICE_URI
    value: http://wallet-ms.blockchain-demo-test.svc:8080
  - name: CURRENCY_CONVERTER_MS_SERVICE_URI
    value: http://currency-converter-ms.blockchain-demo-test.svc:8080
  - name: JAEGER_SERVICE_NAME
    value: test-console-ui
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: jaeger-agent.blockchain-demo-monitoring.svc:5778    
  - name: JAEGER_AGENT_HOST
    value: jaeger-agent.blockchain-demo-monitoring.svc      